spring:
    application:
        name: test-service-a
    jackson:
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm:ss
        default-property-inclusion: non_null
    datasource:
        url: jdbc:mysql://192.168.0.6:3306/ams_file_service?useUnicode=true&characterEncoding=UTF8&allowMultiQueries=true&allowPublicKeyRetrieval=true
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver
        druid:
          initial-size: 1 # 初始化连接大小
          min-idle: 1     # 最小空闲连接数
          max-active: 20  # 最大连接数
          test-on-borrow: true
    redis:
        database: 1
        host: ${REDIS_HOST:ycloud-redis.ycloud}
        port: ${REDIS_PORT:6377}
        password: 1q2w3e4r
        pool:
          max-active: 20
    http:
      multipart:
        enabled: true
        max-file-size: 50MB # 设置单个文件的最大长度
        max-request-size: 50MB # 设置最大的请求文件的大小
        file-size-threshold: 100MB  # 当上传文件达到1MB的时候进行磁盘写入

mybatis:
    type-aliases-package: com.yss.ams.file.mapper
    mapper-locations: classpath:mapper/**/*.xml

logging:
  level:
    com.yss.base.security.admin.mapper: debug
  file: "logs/ams-file-service"

